### PR TITLE
Added save, delete, search, and user icons.

### PR DESCRIPTION
**Pull request by dgreisen**
Hi Isandunk,

Here is a first batch of icons to add to the set. I don't have photoshop, so I simply added the file that I received from our designer. I will have to let you incorporate the file into the project.

Should have another couple icons in the next several weeks. If it would be easier to receive them by email, send me your address. Mine is my username at gmail.

If you could please include an attribution to Allison Johnston allisonjohnston@gmail.com, I'd appreciate it.

Thank you,

David

### CODE REVIEW

**Comment by isandunk** [comment]
Thanks David, I'm going to take a detailed look over them now and see about working them in.

Cheers.

**Comment by isandunk** [comment]
Hi David - these are great, thank you. 

However, before I merge them I think that the trashcan needs slight adjusting - the third (on the right) vertical stripe is not as well defined as the previous two. Once that is adjusted I can pull them in.

What other icons are you thinking of producing? I may have some spare time approaching, so I may add more examples to this repro, but I don't want to duplicate any work that you or Allison might be about to produce.

Cheers.

**Comment by dgreisen** [comment]
Duncan,

re the trashcan: We have already accepted receipt of the icons from
Allison, so we cannot make further changes. You are welcome to modify it or
discard if necessary.

We plan the following three icons within the month:
1. tag
2. add tag
3. follow (eye)

If you provide your email to me, I can send you these icons for review
prior to our acceptance. We will need a 2 day turnaround on your part,
though.

Regards,

David

**Comment by isandunk** [comment]
Just literally had time to work these into the repo(!). Thanks again for the commit.

**Pull request closed without merging**
